### ISSUE TITLE
Translate April 3 COVID-19 report into Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/translations#9]
Hello @tomoyuki-nezu @satotake @fzhang12 !
 
The situation report from 2020-04-03  is ready to be translated to Japanese. 
Branch to translate on: `sit-rep_ja` 
File to translate: https://github.com/nextstrain/translations/blob/sit-rep_ja/narratives/translations_ncov_sit-rep_ja_2020-04-03.md You can translate directly in this file, but please remember to push often as other people may be working on the translation!
Link to preview: https://nextstrain.org/community/narratives/nextstrain/translations@sit-rep_ja/ncov/sit-rep/ja/2020-04-03
 
**Logistics**
Once you’ve accepted my invitation to join the Nextstrain organization and the `translations` repo, you should have access to push to branches. Ping me if you’re having problems.
 
Please update the translations board as you work on the translation: https://github.com/nextstrain/translations/projects/1
 
Please assign yourself to the translation if you’re working on it this week.
 
When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it! 
 
Use the [discussion board for your team](https://github.com/orgs/nextstrain/teams/japanese). Discussion boards are a place for you to communicate together, and unlike issues, they won’t disappear. It’s a good place to sort out translation workflows, post a dictionary for technical terms, whatever you need as a team.
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Japanese-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together.  
 
**Thank you so very much! It’s an honor to fight the pandemic with you. I continue to hope you and your loved ones are well.**

**Comment by tomoyuki-nezu** [comment]
Thank you @cassiawag 
I have a rough translation for about an hour from now on. Please check and fix later > @fzhang12 
 @satotake

**Comment by tomoyuki-nezu** [comment]
@cassiawag It seems that the status cannot be changed because the person (me) has not been assigned this Issue.

**Comment by cassiawag** [comment]
Assign yourself to the issue @tomoyuki-nezu if you can.

**Comment by tomoyuki-nezu** [comment]
@cassiawag It doesn't seem to have push permission.

$ git push
remote: Permission to nextstrain/translations.git denied to tomoyuki-nezu.
fatal: unable to access 'https://github.com/nextstrain/translations.git/': The requested URL returned error: 403

**Comment by tomoyuki-nezu** [comment]
@fzhang12 @satotake
I can't go online much after, so I put the files here. I'll back to night.
https://drive.google.com/file/d/1Ebs2W-lFJo0-GK_VxCaonV8iVQL05guX/view?usp=sharing

**Comment by cassiawag** [comment]
@tomoyuki-nezu -- you need to accept the invitation to join the organization and the repo.

You'll then have permissions :)

**Comment by tomoyuki-nezu** [comment]
@cassiawag I tried it now, but I still can't change the status....

**Comment by tomoyuki-nezu** [comment]
@cassiawag I checked my email, but it looks like my invitation hasn't arrived yet. Same as last time, it takes time maybe... I checked directly via the GitHub API, but could not find the invitation. Check back later. Thanks.

**Comment by tomoyuki-nezu** [comment]
@cassiawag Invite was coming and joined. Thank you.
@fzhang12 @satotake I've pushed the rough translation so please review it.

**Comment by satotake** [comment]
Done and pushed
I tweaked just a few. please check it
Thank you! @tomoyuki-nezu 

we will be happy with your verification, @fzhang12

**Comment by tomoyuki-nezu** [comment]
Checked, Thank you @satotake
There is no modification from me, so please prepare for publish after @fzhang12 confirms.

**Comment by fzhang12** [comment]
Thank you both, I will start working on the proofreading.

**Comment by fzhang12** [comment]
@satotake I noticed you missed a pair of square brackets when dealing with 目次
it made text 1 unable to be recognised. I already fixed it and everything is cool now :)
just maybe next time you would pay a little attention to the brackets

**Comment by fzhang12** [comment]
Hi all, I finished all my changes. You've all done a brilliant job. I did no main editing but just fixing links and new lines. I think the translation is good to go. 
Happy working with all of you. =)

**Comment by fzhang12** [comment]
@satotake @tomoyuki-nezu Maybe one of you can take a final look on the live version? Then I could create the pull request for publication.

**Comment by satotake** [comment]
@fzhang12 checked.
Thank you. They had to be linked with Japanese page as you did!

**Comment by fzhang12** [comment]
@satotake thanks for the final check. It was not me though, @cassiawag updated all the links.
I have created the pull request, thanks all of you for the effort.

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-04-03 ! Thanks all! That seemed especially fast. 

Could someone translate this for the Twitter post for me?

"The latest #COVID19 #SARSCov2 situaton report is now available in Japanese. Thank you Takeshi Sato, @tommy_nezy, and @fengjun_zhang for the rapid translation. 

This week we cover the latest data from Japan, Senegal, Democratic Republic of the Congo, Iceland, Austria, Canada, and the USA."

**Comment by cassiawag** [comment]
I went ahead and posted. Fingers crossed that Google Tranlsate didn't screw it up lol. Have a restful weekend (if you can) :)

**Comment by fzhang12** [comment]
@cassiawag  I am sorry I didnt notice your feedback. I went for a jog and just came back.
Can I do it right now? 
Usually Japanese pronounce has too many possible characters so probably you are not getting satotake's name correct 

" #新型コロナウィルス #COVID19 #SARSCov2 についての状況報告が更新されました。翻訳担当のTakeshi Satoさん、 @tommy_nezy さん、と @fengjun_zhang さんにお疲れ様です。

今週は日本、セネガル、コンゴ民主共和国、アイスランド、オーストリア、カナダと米国の最新データについて報告します"

**Comment by cassiawag** [comment]
No worries @fzhang12. I already posted on Twitter. Let me know if it's truly erroneous and I'll delete and retweet. I don't typically like to do so because enough people have already liked and retweeted it. It's my bad for not asking for the translation initially.

**Comment by tomoyuki-nezu** [comment]
Thank you again and see you next week end.
Have a safe days everyone.

**Comment by tomoyuki-nezu** [comment]
@cassiawag @satotake @falnaji 
Thank you again and see you next week end.
Have a safe days everyone.
